const teamDetailsFormatted = {
  teams: [
    {
      divisionStanding: 1,
      percentile: 0,
      overallStanding: 1,
      teamAbbrev: '�',
      waiverRank: 10,
      teamNickname: 'of Heaven',
      logoUrl: 'http://www.phasmatia.com/images/ChosenOne_MtSkylight.jpg',
      logoType: 'customValid',
      teamId: 1,
      record: {
        awayPercentage: 0,
        divisionStanding: 1,
        overallStanding: 1,
        divisionLosses: 3,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 4,
        streakType: 1,
        overallTies: 0,
        homeTies: 0,
        homeWins: 4,
        divisionTies: 0,
        overallPercentage: 0.61538,
        overallWins: 8,
        overallLosses: 5,
        streakLength: 1,
        pointsAgainst: 1160,
        awayWins: 4,
        divisionPercentage: 0.57143,
        homeLosses: 2,
        pointsFor: 1282,
        awayLosses: 3
      },
      rank: 0,
      division: {
        divisionName: 'Division 2',
        divisionId: 1,
        size: 5
      },
      teamLocation: 'The Mandate',
      owners: [
        {
          lastName: 'Mount',
          primaryOwner: true,
          leagueManager: true,
          joined: true,
          inviteId: 0,
          ownerId: 22456240,
          userProfileId: 22456240,
          photoUrl: 'http://f.espncdn.com/avatars/M Mount/medium',
          firstName: 'Michael'
        }
      ],
      teamName: 'The Mandate of Heaven',
      teamRecord: '8-5-0',
      pointsFor: 1282,
      pointsAgainst: 1160
    },
    {
      divisionStanding: 3,
      percentile: 0,
      overallStanding: 4,
      teamAbbrev: 'SECY',
      waiverRank: 7,
      teamNickname: 'Noise',
      logoUrl: 'https://media.giphy.com/media/l3vR5bWP3axysgZs4/giphy.gif',
      logoType: 'custom',
      teamId: 2,
      record: {
        awayPercentage: 0,
        divisionStanding: 3,
        overallStanding: 4,
        divisionLosses: 2,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 4,
        streakType: 2,
        overallTies: 0,
        homeTies: 0,
        homeWins: 5,
        divisionTies: 0,
        overallPercentage: 0.53846,
        overallWins: 7,
        overallLosses: 6,
        streakLength: 1,
        pointsAgainst: 1209,
        awayWins: 2,
        divisionPercentage: 0.66667,
        homeLosses: 3,
        pointsFor: 1245,
        awayLosses: 3
      },
      rank: 0,
      division: {
        divisionName: 'Division 1',
        divisionId: 0,
        size: 5
      },
      teamLocation: 'The Brown',
      owners: [
        {
          lastName: 'Sa',
          primaryOwner: true,
          leagueManager: false,
          joined: true,
          inviteId: 0,
          ownerId: 23368496,
          userProfileId: 23368496,
          photoUrl: 'http://f.espncdn.com/avatars/mrhockey220/medium',
          firstName: 'Alec'
        }
      ],
      teamName: 'The Brown Noise',
      teamRecord: '7-6-0',
      pointsFor: 1245,
      pointsAgainst: 1209
    },
    {
      divisionStanding: 5,
      percentile: 0,
      overallStanding: 10,
      teamAbbrev: ':(',
      waiverRank: 1,
      teamNickname: 'The Sacko now',
      logoUrl: 'https://uproxx.files.wordpress.com/2015/02/poop-300x231.png?w=650&h=501',
      logoType: 'customValid',
      teamId: 3,
      record: {
        awayPercentage: 0,
        divisionStanding: 5,
        overallStanding: 10,
        divisionLosses: 5,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 2,
        streakType: 2,
        overallTies: 0,
        homeTies: 0,
        homeWins: 2,
        divisionTies: 0,
        overallPercentage: 0.38462,
        overallWins: 5,
        overallLosses: 8,
        streakLength: 2,
        pointsAgainst: 1209,
        awayWins: 3,
        divisionPercentage: 0.28571,
        homeLosses: 5,
        pointsFor: 1084,
        awayLosses: 3
      },
      rank: 0,
      division: {
        divisionName: 'Division 1',
        divisionId: 0,
        size: 5
      },
      teamLocation: 'Look at me I am',
      owners: [
        {
          lastName: 'Nackeeran',
          primaryOwner: true,
          leagueManager: false,
          joined: true,
          inviteId: 0,
          ownerId: 14725639,
          userProfileId: 14725639,
          photoUrl: 'http://f.espncdn.com/avatars/sirpi.raiders/medium',
          firstName: 'Sirpi'
        }
      ],
      teamName: 'Look at me I am The Sacko now',
      teamRecord: '5-8-0',
      pointsFor: 1084,
      pointsAgainst: 1209
    },
    {
      divisionStanding: 4,
      percentile: 0,
      overallStanding: 9,
      teamAbbrev: 'FM2P',
      waiverRank: 2,
      teamNickname: 'To Cousins',
      logoUrl: 'http://i.imgur.com/GzSsbTu.gif',
      logoType: 'custom',
      teamId: 4,
      record: {
        awayPercentage: 0,
        divisionStanding: 4,
        overallStanding: 9,
        divisionLosses: 4,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 4,
        streakType: 1,
        overallTies: 0,
        homeTies: 0,
        homeWins: 3,
        divisionTies: 0,
        overallPercentage: 0.38462,
        overallWins: 5,
        overallLosses: 8,
        streakLength: 1,
        pointsAgainst: 1269,
        awayWins: 2,
        divisionPercentage: 0.5,
        homeLosses: 4,
        pointsFor: 1348,
        awayLosses: 4
      },
      rank: 0,
      division: {
        divisionName: 'Division 1',
        divisionId: 0,
        size: 5
      },
      teamLocation: 'Spreadin Zeke',
      owners: [
        {
          lastName: 'Oatman',
          primaryOwner: true,
          leagueManager: false,
          joined: true,
          inviteId: 0,
          ownerId: 23368802,
          userProfileId: 23368802,
          photoUrl: 'http://f.espncdn.com/avatars/thebigoats/medium',
          firstName: 'Michael'
        }
      ],
      teamName: 'Spreadin Zeke To Cousins',
      teamRecord: '5-8-0',
      pointsFor: 1348,
      pointsAgainst: 1269
    },
    {
      divisionStanding: 2,
      percentile: 0,
      overallStanding: 5,
      teamAbbrev: 'Drew',
      waiverRank: 6,
      teamNickname: 'For President',
      logoUrl: 'http://g.espncdn.com/s/ffllm/logos/AtTheStadium-RobbHarskamp/At_The_Stadium_07.svg',
      logoType: 'vector',
      teamId: 5,
      record: {
        awayPercentage: 0,
        divisionStanding: 2,
        overallStanding: 5,
        divisionLosses: 4,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 1,
        streakType: 2,
        overallTies: 0,
        homeTies: 0,
        homeWins: 2,
        divisionTies: 0,
        overallPercentage: 0.46154,
        overallWins: 6,
        overallLosses: 7,
        streakLength: 2,
        pointsAgainst: 1233,
        awayWins: 4,
        divisionPercentage: 0.2,
        homeLosses: 3,
        pointsFor: 1232,
        awayLosses: 4
      },
      rank: 0,
      division: {
        divisionName: 'Division 2',
        divisionId: 1,
        size: 5
      },
      teamLocation: 'Justin Tucker',
      owners: [
        {
          lastName: 'Babcock',
          primaryOwner: true,
          leagueManager: false,
          joined: true,
          inviteId: 0,
          ownerId: 23266634,
          userProfileId: 23266634,
          photoUrl: 'http://f.espncdn.com/avatars/Ownchez/medium',
          firstName: 'Brian '
        }
      ],
      teamName: 'Justin Tucker For President',
      teamRecord: '6-7-0',
      pointsFor: 1232,
      pointsAgainst: 1233
    },
    {
      divisionStanding: 1,
      percentile: 0,
      overallStanding: 2,
      teamAbbrev: '2on',
      waiverRank: 9,
      teamNickname: 'One',
      logoUrl: 'http://g.espncdn.com/s/ffllm/logos/GridironWarriors-MartinLaksman/warriors-05.svg',
      logoType: 'vector',
      teamId: 9,
      record: {
        awayPercentage: 0,
        divisionStanding: 1,
        overallStanding: 2,
        divisionLosses: 3,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 2,
        streakType: 1,
        overallTies: 0,
        homeTies: 0,
        homeWins: 5,
        divisionTies: 0,
        overallPercentage: 0.61538,
        overallWins: 8,
        overallLosses: 5,
        streakLength: 2,
        pointsAgainst: 1198,
        awayWins: 3,
        divisionPercentage: 0.4,
        homeLosses: 3,
        pointsFor: 1235,
        awayLosses: 2
      },
      rank: 0,
      division: {
        divisionName: 'Division 1',
        divisionId: 0,
        size: 5
      },
      teamLocation: 'The Chosen ',
      owners: [
        {
          lastName: 'Fladger',
          primaryOwner: true,
          leagueManager: false,
          joined: true,
          inviteId: 0,
          ownerId: 29845606,
          userProfileId: 29845606,
          photoUrl: 'http://f.espncdn.com/avatars/grandnightmare/medium',
          firstName: 'Jordan'
        }
      ],
      teamName: 'The Chosen  One',
      teamRecord: '8-5-0',
      pointsFor: 1235,
      pointsAgainst: 1198
    },
    {
      divisionStanding: 5,
      percentile: 0,
      overallStanding: 8,
      teamAbbrev: 'MXCN',
      waiverRank: 3,
      teamNickname: 'Emotioncoaster',
      logoUrl: 'https://media.giphy.com/media/3oriO14yAAnyeoupZ6/giphy.gif',
      logoType: 'customValid',
      teamId: 11,
      record: {
        awayPercentage: 0,
        divisionStanding: 5,
        overallStanding: 8,
        divisionLosses: 5,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 3,
        streakType: 1,
        overallTies: 0,
        homeTies: 0,
        homeWins: 2,
        divisionTies: 0,
        overallPercentage: 0.46154,
        overallWins: 6,
        overallLosses: 7,
        streakLength: 1,
        pointsAgainst: 1107,
        awayWins: 4,
        divisionPercentage: 0.375,
        homeLosses: 4,
        pointsFor: 1052,
        awayLosses: 3
      },
      rank: 0,
      division: {
        divisionName: 'Division 2',
        divisionId: 1,
        size: 5
      },
      teamLocation: "Badillo's",
      owners: [
        {
          lastName: 'Cabrales',
          primaryOwner: true,
          leagueManager: false,
          joined: true,
          inviteId: 0,
          ownerId: 34994352,
          userProfileId: 34994352,
          photoUrl: 'http://f.espncdn.com/avatars/C Cabrales/medium',
          firstName: 'Casey'
        }
      ],
      teamName: "Badillo's Emotioncoaster",
      teamRecord: '6-7-0',
      pointsFor: 1052,
      pointsAgainst: 1107
    },
    {
      divisionStanding: 3,
      percentile: 0,
      overallStanding: 6,
      teamAbbrev: 'Pls',
      waiverRank: 5,
      teamNickname: 'Giv Me Strength',
      logoUrl: 'http://i2.mirror.co.uk/incoming/article8075004.ece/ALTERNATES/s615b/Harambe.jpg',
      logoType: 'customValid',
      teamId: 12,
      record: {
        awayPercentage: 0,
        divisionStanding: 3,
        overallStanding: 6,
        divisionLosses: 2,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 4,
        streakType: 2,
        overallTies: 0,
        homeTies: 0,
        homeWins: 4,
        divisionTies: 0,
        overallPercentage: 0.46154,
        overallWins: 6,
        overallLosses: 7,
        streakLength: 1,
        pointsAgainst: 1275,
        awayWins: 2,
        divisionPercentage: 0.66667,
        homeLosses: 3,
        pointsFor: 1195,
        awayLosses: 4
      },
      rank: 0,
      division: {
        divisionName: 'Division 2',
        divisionId: 1,
        size: 5
      },
      teamLocation: 'Pls Harambe',
      owners: [
        {
          lastName: 'Badillo',
          primaryOwner: true,
          leagueManager: false,
          joined: true,
          inviteId: 0,
          ownerId: 69968088,
          userProfileId: 69968088,
          photoUrl: 'http://f.espncdn.com/avatars/TrexThetruth/medium',
          firstName: 'Brian'
        }
      ],
      teamName: 'Pls Harambe Giv Me Strength',
      teamRecord: '6-7-0',
      pointsFor: 1195,
      pointsAgainst: 1275
    },
    {
      divisionStanding: 4,
      percentile: 0,
      overallStanding: 7,
      teamAbbrev: 'NAKI',
      waiverRank: 4,
      teamNickname: 'Hotlanta',
      logoUrl: 'http://www.totalprosports.com/wp-content/uploads/2010/10/i-love-julio-jones.jpg',
      logoType: 'customValid',
      teamId: 13,
      record: {
        awayPercentage: 0,
        divisionStanding: 4,
        overallStanding: 7,
        divisionLosses: 2,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 4,
        streakType: 2,
        overallTies: 0,
        homeTies: 0,
        homeWins: 3,
        divisionTies: 0,
        overallPercentage: 0.46154,
        overallWins: 6,
        overallLosses: 7,
        streakLength: 1,
        pointsAgainst: 1159,
        awayWins: 3,
        divisionPercentage: 0.66667,
        homeLosses: 2,
        pointsFor: 1128,
        awayLosses: 5
      },
      rank: 0,
      division: {
        divisionName: 'Division 2',
        divisionId: 1,
        size: 5
      },
      teamLocation: "Matt Ryan's",
      owners: [
        {
          lastName: 'Tellakula',
          primaryOwner: true,
          leagueManager: false,
          joined: true,
          inviteId: 0,
          ownerId: 26174624,
          userProfileId: 26174624,
          photoUrl: 'http://f.espncdn.com/avatars/itsthenaki/medium',
          firstName: 'Nikhil'
        }
      ],
      teamName: "Matt Ryan's Hotlanta",
      teamRecord: '6-7-0',
      pointsFor: 1128,
      pointsAgainst: 1159
    },
    {
      divisionStanding: 2,
      percentile: 0,
      overallStanding: 3,
      teamAbbrev: '12',
      waiverRank: 8,
      teamNickname: 'Gost Jew',
      logoUrl: 'http://g.espncdn.com/s/ffllm/logos/TeamKinny-MartinLaksman/TeamKinny-03.svg',
      logoType: 'vector',
      teamId: 14,
      record: {
        awayPercentage: 0,
        divisionStanding: 2,
        overallStanding: 3,
        divisionLosses: 2,
        homePercentage: 0,
        awayTies: 0,
        divisionWins: 4,
        streakType: 1,
        overallTies: 0,
        homeTies: 0,
        homeWins: 2,
        divisionTies: 0,
        overallPercentage: 0.61538,
        overallWins: 8,
        overallLosses: 5,
        streakLength: 3,
        pointsAgainst: 1141,
        awayWins: 6,
        divisionPercentage: 0.66667,
        homeLosses: 4,
        pointsFor: 1159,
        awayLosses: 1
      },
      rank: 0,
      division: {
        divisionName: 'Division 1',
        divisionId: 0,
        size: 5
      },
      teamLocation: 'Dez Nuts',
      owners: [
        {
          lastName: 'knutson',
          primaryOwner: true,
          leagueManager: false,
          joined: true,
          inviteId: 0,
          ownerId: 13231224,
          userProfileId: 13231224,
          photoUrl: 'http://f.espncdn.com/avatars/kooper 777/medium',
          firstName: 'kooper'
        }
      ],
      teamName: 'Dez Nuts Gost Jew',
      teamRecord: '8-5-0',
      pointsFor: 1159,
      pointsAgainst: 1141
    }
  ],
  metadata: {
    leagueId: '298982',
    defaults: {},
    status: 'offseason',
    seasonId: '2016',
  }
};

export default teamDetailsFormatted;
